#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.17929
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hugin.POS.Resource", IsApplication=true)]

namespace Hugin.POS
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Hugin.POS.Common.Resource.String.library_name = Hugin.POS.Resource.String.library_name;
			Hugin.POS.Data.Resource.String.library_name = Hugin.POS.Resource.String.library_name;
			Hugin.POS.Display.Resource.Attribute.buttonBarButtonStyle = Hugin.POS.Resource.Attribute.buttonBarButtonStyle;
			Hugin.POS.Display.Resource.Attribute.buttonBarStyle = Hugin.POS.Resource.Attribute.buttonBarStyle;
			Hugin.POS.Display.Resource.Attribute.customFont = Hugin.POS.Resource.Attribute.customFont;
			Hugin.POS.Display.Resource.Color.aliceblue = Hugin.POS.Resource.Color.aliceblue;
			Hugin.POS.Display.Resource.Color.antiquewhite = Hugin.POS.Resource.Color.antiquewhite;
			Hugin.POS.Display.Resource.Color.aqua = Hugin.POS.Resource.Color.aqua;
			Hugin.POS.Display.Resource.Color.aquamarine = Hugin.POS.Resource.Color.aquamarine;
			Hugin.POS.Display.Resource.Color.azure = Hugin.POS.Resource.Color.azure;
			Hugin.POS.Display.Resource.Color.beige = Hugin.POS.Resource.Color.beige;
			Hugin.POS.Display.Resource.Color.bisque = Hugin.POS.Resource.Color.bisque;
			Hugin.POS.Display.Resource.Color.black = Hugin.POS.Resource.Color.black;
			Hugin.POS.Display.Resource.Color.black_overlay = Hugin.POS.Resource.Color.black_overlay;
			Hugin.POS.Display.Resource.Color.blanchedalmond = Hugin.POS.Resource.Color.blanchedalmond;
			Hugin.POS.Display.Resource.Color.blue = Hugin.POS.Resource.Color.blue;
			Hugin.POS.Display.Resource.Color.blueviolet = Hugin.POS.Resource.Color.blueviolet;
			Hugin.POS.Display.Resource.Color.brown = Hugin.POS.Resource.Color.brown;
			Hugin.POS.Display.Resource.Color.burlywood = Hugin.POS.Resource.Color.burlywood;
			Hugin.POS.Display.Resource.Color.cadetblue = Hugin.POS.Resource.Color.cadetblue;
			Hugin.POS.Display.Resource.Color.chartreuse = Hugin.POS.Resource.Color.chartreuse;
			Hugin.POS.Display.Resource.Color.chocolate = Hugin.POS.Resource.Color.chocolate;
			Hugin.POS.Display.Resource.Color.coral = Hugin.POS.Resource.Color.coral;
			Hugin.POS.Display.Resource.Color.cornflowerblue = Hugin.POS.Resource.Color.cornflowerblue;
			Hugin.POS.Display.Resource.Color.cornsilk = Hugin.POS.Resource.Color.cornsilk;
			Hugin.POS.Display.Resource.Color.crimson = Hugin.POS.Resource.Color.crimson;
			Hugin.POS.Display.Resource.Color.cyan = Hugin.POS.Resource.Color.cyan;
			Hugin.POS.Display.Resource.Color.darkblue = Hugin.POS.Resource.Color.darkblue;
			Hugin.POS.Display.Resource.Color.darkcyan = Hugin.POS.Resource.Color.darkcyan;
			Hugin.POS.Display.Resource.Color.darkgoldenrod = Hugin.POS.Resource.Color.darkgoldenrod;
			Hugin.POS.Display.Resource.Color.darkgray = Hugin.POS.Resource.Color.darkgray;
			Hugin.POS.Display.Resource.Color.darkgreen = Hugin.POS.Resource.Color.darkgreen;
			Hugin.POS.Display.Resource.Color.darkkhaki = Hugin.POS.Resource.Color.darkkhaki;
			Hugin.POS.Display.Resource.Color.darkmagenta = Hugin.POS.Resource.Color.darkmagenta;
			Hugin.POS.Display.Resource.Color.darkolivegreen = Hugin.POS.Resource.Color.darkolivegreen;
			Hugin.POS.Display.Resource.Color.darkorange = Hugin.POS.Resource.Color.darkorange;
			Hugin.POS.Display.Resource.Color.darkorchid = Hugin.POS.Resource.Color.darkorchid;
			Hugin.POS.Display.Resource.Color.darkred = Hugin.POS.Resource.Color.darkred;
			Hugin.POS.Display.Resource.Color.darksalmon = Hugin.POS.Resource.Color.darksalmon;
			Hugin.POS.Display.Resource.Color.darkseagreen = Hugin.POS.Resource.Color.darkseagreen;
			Hugin.POS.Display.Resource.Color.darkslateblue = Hugin.POS.Resource.Color.darkslateblue;
			Hugin.POS.Display.Resource.Color.darkslategray = Hugin.POS.Resource.Color.darkslategray;
			Hugin.POS.Display.Resource.Color.darkturquoise = Hugin.POS.Resource.Color.darkturquoise;
			Hugin.POS.Display.Resource.Color.darkviolet = Hugin.POS.Resource.Color.darkviolet;
			Hugin.POS.Display.Resource.Color.deeppink = Hugin.POS.Resource.Color.deeppink;
			Hugin.POS.Display.Resource.Color.deepskyblue = Hugin.POS.Resource.Color.deepskyblue;
			Hugin.POS.Display.Resource.Color.dimgray = Hugin.POS.Resource.Color.dimgray;
			Hugin.POS.Display.Resource.Color.dodgerblue = Hugin.POS.Resource.Color.dodgerblue;
			Hugin.POS.Display.Resource.Color.executeend = Hugin.POS.Resource.Color.executeend;
			Hugin.POS.Display.Resource.Color.executestart = Hugin.POS.Resource.Color.executestart;
			Hugin.POS.Display.Resource.Color.firebrick = Hugin.POS.Resource.Color.firebrick;
			Hugin.POS.Display.Resource.Color.floralwhite = Hugin.POS.Resource.Color.floralwhite;
			Hugin.POS.Display.Resource.Color.fncend = Hugin.POS.Resource.Color.fncend;
			Hugin.POS.Display.Resource.Color.fncstart = Hugin.POS.Resource.Color.fncstart;
			Hugin.POS.Display.Resource.Color.forestgreen = Hugin.POS.Resource.Color.forestgreen;
			Hugin.POS.Display.Resource.Color.fuchsia = Hugin.POS.Resource.Color.fuchsia;
			Hugin.POS.Display.Resource.Color.gainsboro = Hugin.POS.Resource.Color.gainsboro;
			Hugin.POS.Display.Resource.Color.ghostwhite = Hugin.POS.Resource.Color.ghostwhite;
			Hugin.POS.Display.Resource.Color.gold = Hugin.POS.Resource.Color.gold;
			Hugin.POS.Display.Resource.Color.goldenrod = Hugin.POS.Resource.Color.goldenrod;
			Hugin.POS.Display.Resource.Color.gray = Hugin.POS.Resource.Color.gray;
			Hugin.POS.Display.Resource.Color.green = Hugin.POS.Resource.Color.green;
			Hugin.POS.Display.Resource.Color.greenyellow = Hugin.POS.Resource.Color.greenyellow;
			Hugin.POS.Display.Resource.Color.honeydew = Hugin.POS.Resource.Color.honeydew;
			Hugin.POS.Display.Resource.Color.hotpink = Hugin.POS.Resource.Color.hotpink;
			Hugin.POS.Display.Resource.Color.indianred = Hugin.POS.Resource.Color.indianred;
			Hugin.POS.Display.Resource.Color.indigo = Hugin.POS.Resource.Color.indigo;
			Hugin.POS.Display.Resource.Color.ivory = Hugin.POS.Resource.Color.ivory;
			Hugin.POS.Display.Resource.Color.khaki = Hugin.POS.Resource.Color.khaki;
			Hugin.POS.Display.Resource.Color.lavender = Hugin.POS.Resource.Color.lavender;
			Hugin.POS.Display.Resource.Color.lavenderblush = Hugin.POS.Resource.Color.lavenderblush;
			Hugin.POS.Display.Resource.Color.lawngreen = Hugin.POS.Resource.Color.lawngreen;
			Hugin.POS.Display.Resource.Color.lemonchiffon = Hugin.POS.Resource.Color.lemonchiffon;
			Hugin.POS.Display.Resource.Color.lightblue = Hugin.POS.Resource.Color.lightblue;
			Hugin.POS.Display.Resource.Color.lightcoral = Hugin.POS.Resource.Color.lightcoral;
			Hugin.POS.Display.Resource.Color.lightcyan = Hugin.POS.Resource.Color.lightcyan;
			Hugin.POS.Display.Resource.Color.lightgoldenrodyellow = Hugin.POS.Resource.Color.lightgoldenrodyellow;
			Hugin.POS.Display.Resource.Color.lightgreen = Hugin.POS.Resource.Color.lightgreen;
			Hugin.POS.Display.Resource.Color.lightgrey = Hugin.POS.Resource.Color.lightgrey;
			Hugin.POS.Display.Resource.Color.lightpink = Hugin.POS.Resource.Color.lightpink;
			Hugin.POS.Display.Resource.Color.lightsalmon = Hugin.POS.Resource.Color.lightsalmon;
			Hugin.POS.Display.Resource.Color.lightseagreen = Hugin.POS.Resource.Color.lightseagreen;
			Hugin.POS.Display.Resource.Color.lightskyblue = Hugin.POS.Resource.Color.lightskyblue;
			Hugin.POS.Display.Resource.Color.lightslategray = Hugin.POS.Resource.Color.lightslategray;
			Hugin.POS.Display.Resource.Color.lightsteelblue = Hugin.POS.Resource.Color.lightsteelblue;
			Hugin.POS.Display.Resource.Color.lightyellow = Hugin.POS.Resource.Color.lightyellow;
			Hugin.POS.Display.Resource.Color.lime = Hugin.POS.Resource.Color.lime;
			Hugin.POS.Display.Resource.Color.limegreen = Hugin.POS.Resource.Color.limegreen;
			Hugin.POS.Display.Resource.Color.linen = Hugin.POS.Resource.Color.linen;
			Hugin.POS.Display.Resource.Color.magenta = Hugin.POS.Resource.Color.magenta;
			Hugin.POS.Display.Resource.Color.maroon = Hugin.POS.Resource.Color.maroon;
			Hugin.POS.Display.Resource.Color.mediumaquamarine = Hugin.POS.Resource.Color.mediumaquamarine;
			Hugin.POS.Display.Resource.Color.mediumblue = Hugin.POS.Resource.Color.mediumblue;
			Hugin.POS.Display.Resource.Color.mediumorchid = Hugin.POS.Resource.Color.mediumorchid;
			Hugin.POS.Display.Resource.Color.mediumpurple = Hugin.POS.Resource.Color.mediumpurple;
			Hugin.POS.Display.Resource.Color.mediumseagreen = Hugin.POS.Resource.Color.mediumseagreen;
			Hugin.POS.Display.Resource.Color.mediumslateblue = Hugin.POS.Resource.Color.mediumslateblue;
			Hugin.POS.Display.Resource.Color.mediumspringgreen = Hugin.POS.Resource.Color.mediumspringgreen;
			Hugin.POS.Display.Resource.Color.mediumturquoise = Hugin.POS.Resource.Color.mediumturquoise;
			Hugin.POS.Display.Resource.Color.mediumvioletred = Hugin.POS.Resource.Color.mediumvioletred;
			Hugin.POS.Display.Resource.Color.menuend = Hugin.POS.Resource.Color.menuend;
			Hugin.POS.Display.Resource.Color.menustart = Hugin.POS.Resource.Color.menustart;
			Hugin.POS.Display.Resource.Color.midnightblue = Hugin.POS.Resource.Color.midnightblue;
			Hugin.POS.Display.Resource.Color.mintcream = Hugin.POS.Resource.Color.mintcream;
			Hugin.POS.Display.Resource.Color.mistyrose = Hugin.POS.Resource.Color.mistyrose;
			Hugin.POS.Display.Resource.Color.moccasin = Hugin.POS.Resource.Color.moccasin;
			Hugin.POS.Display.Resource.Color.navajowhite = Hugin.POS.Resource.Color.navajowhite;
			Hugin.POS.Display.Resource.Color.navy = Hugin.POS.Resource.Color.navy;
			Hugin.POS.Display.Resource.Color.numend = Hugin.POS.Resource.Color.numend;
			Hugin.POS.Display.Resource.Color.numstart = Hugin.POS.Resource.Color.numstart;
			Hugin.POS.Display.Resource.Color.oldlace = Hugin.POS.Resource.Color.oldlace;
			Hugin.POS.Display.Resource.Color.olive = Hugin.POS.Resource.Color.olive;
			Hugin.POS.Display.Resource.Color.olivedrab = Hugin.POS.Resource.Color.olivedrab;
			Hugin.POS.Display.Resource.Color.optend = Hugin.POS.Resource.Color.optend;
			Hugin.POS.Display.Resource.Color.optstart = Hugin.POS.Resource.Color.optstart;
			Hugin.POS.Display.Resource.Color.orange = Hugin.POS.Resource.Color.orange;
			Hugin.POS.Display.Resource.Color.orangered = Hugin.POS.Resource.Color.orangered;
			Hugin.POS.Display.Resource.Color.orchid = Hugin.POS.Resource.Color.orchid;
			Hugin.POS.Display.Resource.Color.palegoldenrod = Hugin.POS.Resource.Color.palegoldenrod;
			Hugin.POS.Display.Resource.Color.palegreen = Hugin.POS.Resource.Color.palegreen;
			Hugin.POS.Display.Resource.Color.paleturquoise = Hugin.POS.Resource.Color.paleturquoise;
			Hugin.POS.Display.Resource.Color.palevioletred = Hugin.POS.Resource.Color.palevioletred;
			Hugin.POS.Display.Resource.Color.papayawhip = Hugin.POS.Resource.Color.papayawhip;
			Hugin.POS.Display.Resource.Color.peachpuff = Hugin.POS.Resource.Color.peachpuff;
			Hugin.POS.Display.Resource.Color.peru = Hugin.POS.Resource.Color.peru;
			Hugin.POS.Display.Resource.Color.pink = Hugin.POS.Resource.Color.pink;
			Hugin.POS.Display.Resource.Color.pluend = Hugin.POS.Resource.Color.pluend;
			Hugin.POS.Display.Resource.Color.plum = Hugin.POS.Resource.Color.plum;
			Hugin.POS.Display.Resource.Color.plustart = Hugin.POS.Resource.Color.plustart;
			Hugin.POS.Display.Resource.Color.powderblue = Hugin.POS.Resource.Color.powderblue;
			Hugin.POS.Display.Resource.Color.purple = Hugin.POS.Resource.Color.purple;
			Hugin.POS.Display.Resource.Color.red = Hugin.POS.Resource.Color.red;
			Hugin.POS.Display.Resource.Color.rosybrown = Hugin.POS.Resource.Color.rosybrown;
			Hugin.POS.Display.Resource.Color.royalblue = Hugin.POS.Resource.Color.royalblue;
			Hugin.POS.Display.Resource.Color.saddlebrown = Hugin.POS.Resource.Color.saddlebrown;
			Hugin.POS.Display.Resource.Color.salmon = Hugin.POS.Resource.Color.salmon;
			Hugin.POS.Display.Resource.Color.sandybrown = Hugin.POS.Resource.Color.sandybrown;
			Hugin.POS.Display.Resource.Color.seagreen = Hugin.POS.Resource.Color.seagreen;
			Hugin.POS.Display.Resource.Color.seashell = Hugin.POS.Resource.Color.seashell;
			Hugin.POS.Display.Resource.Color.sienna = Hugin.POS.Resource.Color.sienna;
			Hugin.POS.Display.Resource.Color.silver = Hugin.POS.Resource.Color.silver;
			Hugin.POS.Display.Resource.Color.skyblue = Hugin.POS.Resource.Color.skyblue;
			Hugin.POS.Display.Resource.Color.slateblue = Hugin.POS.Resource.Color.slateblue;
			Hugin.POS.Display.Resource.Color.slategray = Hugin.POS.Resource.Color.slategray;
			Hugin.POS.Display.Resource.Color.snow = Hugin.POS.Resource.Color.snow;
			Hugin.POS.Display.Resource.Color.springgreen = Hugin.POS.Resource.Color.springgreen;
			Hugin.POS.Display.Resource.Color.steelblue = Hugin.POS.Resource.Color.steelblue;
			Hugin.POS.Display.Resource.Color.tan = Hugin.POS.Resource.Color.tan;
			Hugin.POS.Display.Resource.Color.teal = Hugin.POS.Resource.Color.teal;
			Hugin.POS.Display.Resource.Color.thistle = Hugin.POS.Resource.Color.thistle;
			Hugin.POS.Display.Resource.Color.tomato = Hugin.POS.Resource.Color.tomato;
			Hugin.POS.Display.Resource.Color.turquoise = Hugin.POS.Resource.Color.turquoise;
			Hugin.POS.Display.Resource.Color.violet = Hugin.POS.Resource.Color.violet;
			Hugin.POS.Display.Resource.Color.wheat = Hugin.POS.Resource.Color.wheat;
			Hugin.POS.Display.Resource.Color.white = Hugin.POS.Resource.Color.white;
			Hugin.POS.Display.Resource.Color.whitesmoke = Hugin.POS.Resource.Color.whitesmoke;
			Hugin.POS.Display.Resource.Color.yellow = Hugin.POS.Resource.Color.yellow;
			Hugin.POS.Display.Resource.Color.yellowgreen = Hugin.POS.Resource.Color.yellowgreen;
			Hugin.POS.Display.Resource.Dimension.buttonsEnterHeight = Hugin.POS.Resource.Dimension.buttonsEnterHeight;
			Hugin.POS.Display.Resource.Dimension.buttonsEscapeHeight = Hugin.POS.Resource.Dimension.buttonsEscapeHeight;
			Hugin.POS.Display.Resource.Dimension.buttonsLeftWidth = Hugin.POS.Resource.Dimension.buttonsLeftWidth;
			Hugin.POS.Display.Resource.Dimension.buttonsPadding = Hugin.POS.Resource.Dimension.buttonsPadding;
			Hugin.POS.Display.Resource.Dimension.buttonsRightWidth = Hugin.POS.Resource.Dimension.buttonsRightWidth;
			Hugin.POS.Display.Resource.Dimension.keyHeight = Hugin.POS.Resource.Dimension.keyHeight;
			Hugin.POS.Display.Resource.Dimension.keyWidth = Hugin.POS.Resource.Dimension.keyWidth;
			Hugin.POS.Display.Resource.Dimension.keysHeight = Hugin.POS.Resource.Dimension.keysHeight;
			Hugin.POS.Display.Resource.Dimension.lcdAreaHeight = Hugin.POS.Resource.Dimension.lcdAreaHeight;
			Hugin.POS.Display.Resource.Dimension.lcdAreaHeightHor = Hugin.POS.Resource.Dimension.lcdAreaHeightHor;
			Hugin.POS.Display.Resource.Dimension.lcdAreaWidth = Hugin.POS.Resource.Dimension.lcdAreaWidth;
			Hugin.POS.Display.Resource.Dimension.lcdHeight = Hugin.POS.Resource.Dimension.lcdHeight;
			Hugin.POS.Display.Resource.Dimension.lcdWidth = Hugin.POS.Resource.Dimension.lcdWidth;
			Hugin.POS.Display.Resource.Drawable.banner = Hugin.POS.Resource.Drawable.banner;
			Hugin.POS.Display.Resource.Drawable.exec_bg = Hugin.POS.Resource.Drawable.exec_bg;
			Hugin.POS.Display.Resource.Drawable.fncs_bg = Hugin.POS.Resource.Drawable.fncs_bg;
			Hugin.POS.Display.Resource.Drawable.Icon = Hugin.POS.Resource.Drawable.Icon;
			Hugin.POS.Display.Resource.Drawable.menu_bg = Hugin.POS.Resource.Drawable.menu_bg;
			Hugin.POS.Display.Resource.Drawable.num_bg = Hugin.POS.Resource.Drawable.num_bg;
			Hugin.POS.Display.Resource.Drawable.opts_bg = Hugin.POS.Resource.Drawable.opts_bg;
			Hugin.POS.Display.Resource.Drawable.plu_bg = Hugin.POS.Resource.Drawable.plu_bg;
			Hugin.POS.Display.Resource.Id.Buttons = Hugin.POS.Resource.Id.Buttons;
			Hugin.POS.Display.Resource.Id.Buttons1 = Hugin.POS.Resource.Id.Buttons1;
			Hugin.POS.Display.Resource.Id.Buttons10 = Hugin.POS.Resource.Id.Buttons10;
			Hugin.POS.Display.Resource.Id.Buttons11 = Hugin.POS.Resource.Id.Buttons11;
			Hugin.POS.Display.Resource.Id.Buttons2 = Hugin.POS.Resource.Id.Buttons2;
			Hugin.POS.Display.Resource.Id.Buttons3 = Hugin.POS.Resource.Id.Buttons3;
			Hugin.POS.Display.Resource.Id.Buttons4 = Hugin.POS.Resource.Id.Buttons4;
			Hugin.POS.Display.Resource.Id.Buttons5 = Hugin.POS.Resource.Id.Buttons5;
			Hugin.POS.Display.Resource.Id.Buttons6 = Hugin.POS.Resource.Id.Buttons6;
			Hugin.POS.Display.Resource.Id.Buttons7 = Hugin.POS.Resource.Id.Buttons7;
			Hugin.POS.Display.Resource.Id.Buttons8 = Hugin.POS.Resource.Id.Buttons8;
			Hugin.POS.Display.Resource.Id.Buttons9 = Hugin.POS.Resource.Id.Buttons9;
			Hugin.POS.Display.Resource.Id.ButtonsLeft = Hugin.POS.Resource.Id.ButtonsLeft;
			Hugin.POS.Display.Resource.Id.ButtonsRight = Hugin.POS.Resource.Id.ButtonsRight;
			Hugin.POS.Display.Resource.Id.button1_1 = Hugin.POS.Resource.Id.button1_1;
			Hugin.POS.Display.Resource.Id.button1_2 = Hugin.POS.Resource.Id.button1_2;
			Hugin.POS.Display.Resource.Id.button1_3 = Hugin.POS.Resource.Id.button1_3;
			Hugin.POS.Display.Resource.Id.button1_4 = Hugin.POS.Resource.Id.button1_4;
			Hugin.POS.Display.Resource.Id.button1_5 = Hugin.POS.Resource.Id.button1_5;
			Hugin.POS.Display.Resource.Id.button1_6 = Hugin.POS.Resource.Id.button1_6;
			Hugin.POS.Display.Resource.Id.button2_1 = Hugin.POS.Resource.Id.button2_1;
			Hugin.POS.Display.Resource.Id.button2_2 = Hugin.POS.Resource.Id.button2_2;
			Hugin.POS.Display.Resource.Id.button2_3 = Hugin.POS.Resource.Id.button2_3;
			Hugin.POS.Display.Resource.Id.button2_4 = Hugin.POS.Resource.Id.button2_4;
			Hugin.POS.Display.Resource.Id.button2_5 = Hugin.POS.Resource.Id.button2_5;
			Hugin.POS.Display.Resource.Id.button2_6 = Hugin.POS.Resource.Id.button2_6;
			Hugin.POS.Display.Resource.Id.button2_7 = Hugin.POS.Resource.Id.button2_7;
			Hugin.POS.Display.Resource.Id.button2_8 = Hugin.POS.Resource.Id.button2_8;
			Hugin.POS.Display.Resource.Id.button3_1 = Hugin.POS.Resource.Id.button3_1;
			Hugin.POS.Display.Resource.Id.button3_2 = Hugin.POS.Resource.Id.button3_2;
			Hugin.POS.Display.Resource.Id.button3_3 = Hugin.POS.Resource.Id.button3_3;
			Hugin.POS.Display.Resource.Id.button3_4 = Hugin.POS.Resource.Id.button3_4;
			Hugin.POS.Display.Resource.Id.button3_5 = Hugin.POS.Resource.Id.button3_5;
			Hugin.POS.Display.Resource.Id.button3_6 = Hugin.POS.Resource.Id.button3_6;
			Hugin.POS.Display.Resource.Id.button3_7 = Hugin.POS.Resource.Id.button3_7;
			Hugin.POS.Display.Resource.Id.button3_8 = Hugin.POS.Resource.Id.button3_8;
			Hugin.POS.Display.Resource.Id.button4_1 = Hugin.POS.Resource.Id.button4_1;
			Hugin.POS.Display.Resource.Id.button4_2 = Hugin.POS.Resource.Id.button4_2;
			Hugin.POS.Display.Resource.Id.button4_3 = Hugin.POS.Resource.Id.button4_3;
			Hugin.POS.Display.Resource.Id.button4_4 = Hugin.POS.Resource.Id.button4_4;
			Hugin.POS.Display.Resource.Id.button4_5 = Hugin.POS.Resource.Id.button4_5;
			Hugin.POS.Display.Resource.Id.button4_6 = Hugin.POS.Resource.Id.button4_6;
			Hugin.POS.Display.Resource.Id.button4_7 = Hugin.POS.Resource.Id.button4_7;
			Hugin.POS.Display.Resource.Id.button4_8 = Hugin.POS.Resource.Id.button4_8;
			Hugin.POS.Display.Resource.Id.button5_1 = Hugin.POS.Resource.Id.button5_1;
			Hugin.POS.Display.Resource.Id.button5_2 = Hugin.POS.Resource.Id.button5_2;
			Hugin.POS.Display.Resource.Id.button5_3 = Hugin.POS.Resource.Id.button5_3;
			Hugin.POS.Display.Resource.Id.button5_4 = Hugin.POS.Resource.Id.button5_4;
			Hugin.POS.Display.Resource.Id.button5_5 = Hugin.POS.Resource.Id.button5_5;
			Hugin.POS.Display.Resource.Id.button5_6 = Hugin.POS.Resource.Id.button5_6;
			Hugin.POS.Display.Resource.Id.button5_7 = Hugin.POS.Resource.Id.button5_7;
			Hugin.POS.Display.Resource.Id.button5_8 = Hugin.POS.Resource.Id.button5_8;
			Hugin.POS.Display.Resource.Id.button6_1 = Hugin.POS.Resource.Id.button6_1;
			Hugin.POS.Display.Resource.Id.button6_2 = Hugin.POS.Resource.Id.button6_2;
			Hugin.POS.Display.Resource.Id.button6_3 = Hugin.POS.Resource.Id.button6_3;
			Hugin.POS.Display.Resource.Id.button6_4 = Hugin.POS.Resource.Id.button6_4;
			Hugin.POS.Display.Resource.Id.button6_5 = Hugin.POS.Resource.Id.button6_5;
			Hugin.POS.Display.Resource.Id.button6_6 = Hugin.POS.Resource.Id.button6_6;
			Hugin.POS.Display.Resource.Id.button6_7 = Hugin.POS.Resource.Id.button6_7;
			Hugin.POS.Display.Resource.Id.horLayLCD1 = Hugin.POS.Resource.Id.horLayLCD1;
			Hugin.POS.Display.Resource.Id.horTop = Hugin.POS.Resource.Id.horTop;
			Hugin.POS.Display.Resource.Id.imageView1 = Hugin.POS.Resource.Id.imageView1;
			Hugin.POS.Display.Resource.Id.layAll = Hugin.POS.Resource.Id.layAll;
			Hugin.POS.Display.Resource.Id.layImage = Hugin.POS.Resource.Id.layImage;
			Hugin.POS.Display.Resource.Id.textView1 = Hugin.POS.Resource.Id.textView1;
			Hugin.POS.Display.Resource.Id.textView2 = Hugin.POS.Resource.Id.textView2;
			Hugin.POS.Display.Resource.Layout.Main = Hugin.POS.Resource.Layout.Main;
			Hugin.POS.Display.Resource.String.Amount = Hugin.POS.Resource.String.Amount;
			Hugin.POS.Display.Resource.String.Correct = Hugin.POS.Resource.String.Correct;
			Hugin.POS.Display.Resource.String.Customer = Hugin.POS.Resource.String.Customer;
			Hugin.POS.Display.Resource.String.Document = Hugin.POS.Resource.String.Document;
			Hugin.POS.Display.Resource.String.Drawer = Hugin.POS.Resource.String.Drawer;
			Hugin.POS.Display.Resource.String.Enter = Hugin.POS.Resource.String.Enter;
			Hugin.POS.Display.Resource.String.Escape = Hugin.POS.Resource.String.Escape;
			Hugin.POS.Display.Resource.String.In = Hugin.POS.Resource.String.In;
			Hugin.POS.Display.Resource.String.LCD1 = Hugin.POS.Resource.String.LCD1;
			Hugin.POS.Display.Resource.String.LCD2 = Hugin.POS.Resource.String.LCD2;
			Hugin.POS.Display.Resource.String.Num0 = Hugin.POS.Resource.String.Num0;
			Hugin.POS.Display.Resource.String.Num1 = Hugin.POS.Resource.String.Num1;
			Hugin.POS.Display.Resource.String.Num2 = Hugin.POS.Resource.String.Num2;
			Hugin.POS.Display.Resource.String.Num3 = Hugin.POS.Resource.String.Num3;
			Hugin.POS.Display.Resource.String.Num4 = Hugin.POS.Resource.String.Num4;
			Hugin.POS.Display.Resource.String.Num5 = Hugin.POS.Resource.String.Num5;
			Hugin.POS.Display.Resource.String.Num6 = Hugin.POS.Resource.String.Num6;
			Hugin.POS.Display.Resource.String.Num7 = Hugin.POS.Resource.String.Num7;
			Hugin.POS.Display.Resource.String.Num8 = Hugin.POS.Resource.String.Num8;
			Hugin.POS.Display.Resource.String.Num9 = Hugin.POS.Resource.String.Num9;
			Hugin.POS.Display.Resource.String.Option = Hugin.POS.Resource.String.Option;
			Hugin.POS.Display.Resource.String.Out = Hugin.POS.Resource.String.Out;
			Hugin.POS.Display.Resource.String.PLU = Hugin.POS.Resource.String.PLU;
			Hugin.POS.Display.Resource.String.Paper = Hugin.POS.Resource.String.Paper;
			Hugin.POS.Display.Resource.String.Price = Hugin.POS.Resource.String.Price;
			Hugin.POS.Display.Resource.String.Program = Hugin.POS.Resource.String.Program;
			Hugin.POS.Display.Resource.String.Report = Hugin.POS.Resource.String.Report;
			Hugin.POS.Display.Resource.String.Seller = Hugin.POS.Resource.String.Seller;
			Hugin.POS.Display.Resource.String.Seperator = Hugin.POS.Resource.String.Seperator;
			Hugin.POS.Display.Resource.String.Subtotal = Hugin.POS.Resource.String.Subtotal;
			Hugin.POS.Display.Resource.String.app_name = Hugin.POS.Resource.String.app_name;
			Hugin.POS.Display.Resource.String.library_name = Hugin.POS.Resource.String.library_name;
			Hugin.POS.Display.Resource.Style.AppBaseTheme = Hugin.POS.Resource.Style.AppBaseTheme;
			Hugin.POS.Display.Resource.Style.AppTheme = Hugin.POS.Resource.Style.AppTheme;
			Hugin.POS.Display.Resource.Style.ButtonBar = Hugin.POS.Resource.Style.ButtonBar;
			Hugin.POS.Display.Resource.Style.ButtonBarButton = Hugin.POS.Resource.Style.ButtonBarButton;
			Hugin.POS.Display.Resource.Style.EnterExitStyle = Hugin.POS.Resource.Style.EnterExitStyle;
			Hugin.POS.Display.Resource.Style.FncsStyle = Hugin.POS.Resource.Style.FncsStyle;
			Hugin.POS.Display.Resource.Style.FullscreenTheme = Hugin.POS.Resource.Style.FullscreenTheme;
			Hugin.POS.Display.Resource.Style.MenuStyle = Hugin.POS.Resource.Style.MenuStyle;
			Hugin.POS.Display.Resource.Style.NumStyle = Hugin.POS.Resource.Style.NumStyle;
			Hugin.POS.Display.Resource.Style.OptsStyle = Hugin.POS.Resource.Style.OptsStyle;
			Hugin.POS.Display.Resource.Style.PluStyle = Hugin.POS.Resource.Style.PluStyle;
			Hugin.POS.Display.Resource.Styleable.ButtonBarContainerTheme = Hugin.POS.Resource.Styleable.ButtonBarContainerTheme;
			Hugin.POS.Display.Resource.Styleable.ButtonBarContainerTheme_buttonBarButtonStyle = Hugin.POS.Resource.Styleable.ButtonBarContainerTheme_buttonBarButtonStyle;
			Hugin.POS.Display.Resource.Styleable.ButtonBarContainerTheme_buttonBarStyle = Hugin.POS.Resource.Styleable.ButtonBarContainerTheme_buttonBarStyle;
			Hugin.POS.Display.Resource.Styleable.CustomFonts = Hugin.POS.Resource.Styleable.CustomFonts;
			Hugin.POS.Display.Resource.Styleable.CustomFonts_customFont = Hugin.POS.Resource.Styleable.CustomFonts_customFont;
			Hugin.POS.Security.Resource.String.library_name = Hugin.POS.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int buttonBarButtonStyle = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int buttonBarStyle = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int customFont = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05002d
			public const int aliceblue = 2131034157;
			
			// aapt resource value: 0x7f050023
			public const int antiquewhite = 2131034147;
			
			// aapt resource value: 0x7f05007d
			public const int aqua = 2131034237;
			
			// aapt resource value: 0x7f050062
			public const int aquamarine = 2131034210;
			
			// aapt resource value: 0x7f05002b
			public const int azure = 2131034155;
			
			// aapt resource value: 0x7f050028
			public const int beige = 2131034152;
			
			// aapt resource value: 0x7f05000e
			public const int bisque = 2131034126;
			
			// aapt resource value: 0x7f05008c
			public const int black = 2131034252;
			
			// aapt resource value: 0x7f050000
			public const int black_overlay = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int blanchedalmond = 2131034124;
			
			// aapt resource value: 0x7f050088
			public const int blue = 2131034248;
			
			// aapt resource value: 0x7f05005b
			public const int blueviolet = 2131034203;
			
			// aapt resource value: 0x7f05004f
			public const int brown = 2131034191;
			
			// aapt resource value: 0x7f050035
			public const int burlywood = 2131034165;
			
			// aapt resource value: 0x7f05006d
			public const int cadetblue = 2131034221;
			
			// aapt resource value: 0x7f050063
			public const int chartreuse = 2131034211;
			
			// aapt resource value: 0x7f05003f
			public const int chocolate = 2131034175;
			
			// aapt resource value: 0x7f050018
			public const int coral = 2131034136;
			
			// aapt resource value: 0x7f05006c
			public const int cornflowerblue = 2131034220;
			
			// aapt resource value: 0x7f050008
			public const int cornsilk = 2131034120;
			
			// aapt resource value: 0x7f050038
			public const int crimson = 2131034168;
			
			// aapt resource value: 0x7f05007e
			public const int cyan = 2131034238;
			
			// aapt resource value: 0x7f05008a
			public const int darkblue = 2131034250;
			
			// aapt resource value: 0x7f050084
			public const int darkcyan = 2131034244;
			
			// aapt resource value: 0x7f050047
			public const int darkgoldenrod = 2131034183;
			
			// aapt resource value: 0x7f05004e
			public const int darkgray = 2131034190;
			
			// aapt resource value: 0x7f050087
			public const int darkgreen = 2131034247;
			
			// aapt resource value: 0x7f050044
			public const int darkkhaki = 2131034180;
			
			// aapt resource value: 0x7f050059
			public const int darkmagenta = 2131034201;
			
			// aapt resource value: 0x7f05006e
			public const int darkolivegreen = 2131034222;
			
			// aapt resource value: 0x7f050017
			public const int darkorange = 2131034135;
			
			// aapt resource value: 0x7f050052
			public const int darkorchid = 2131034194;
			
			// aapt resource value: 0x7f05005a
			public const int darkred = 2131034202;
			
			// aapt resource value: 0x7f050032
			public const int darksalmon = 2131034162;
			
			// aapt resource value: 0x7f050057
			public const int darkseagreen = 2131034199;
			
			// aapt resource value: 0x7f050071
			public const int darkslateblue = 2131034225;
			
			// aapt resource value: 0x7f050077
			public const int darkslategray = 2131034231;
			
			// aapt resource value: 0x7f050082
			public const int darkturquoise = 2131034242;
			
			// aapt resource value: 0x7f050054
			public const int darkviolet = 2131034196;
			
			// aapt resource value: 0x7f05001c
			public const int deeppink = 2131034140;
			
			// aapt resource value: 0x7f050083
			public const int deepskyblue = 2131034243;
			
			// aapt resource value: 0x7f05006a
			public const int dimgray = 2131034218;
			
			// aapt resource value: 0x7f05007b
			public const int dodgerblue = 2131034235;
			
			// aapt resource value: 0x7f050098
			public const int executeend = 2131034264;
			
			// aapt resource value: 0x7f050097
			public const int executestart = 2131034263;
			
			// aapt resource value: 0x7f050048
			public const int firebrick = 2131034184;
			
			// aapt resource value: 0x7f050006
			public const int floralwhite = 2131034118;
			
			// aapt resource value: 0x7f050094
			public const int fncend = 2131034260;
			
			// aapt resource value: 0x7f050093
			public const int fncstart = 2131034259;
			
			// aapt resource value: 0x7f050079
			public const int forestgreen = 2131034233;
			
			// aapt resource value: 0x7f05001d
			public const int fuchsia = 2131034141;
			
			// aapt resource value: 0x7f050037
			public const int gainsboro = 2131034167;
			
			// aapt resource value: 0x7f050025
			public const int ghostwhite = 2131034149;
			
			// aapt resource value: 0x7f050012
			public const int gold = 2131034130;
			
			// aapt resource value: 0x7f05003a
			public const int goldenrod = 2131034170;
			
			// aapt resource value: 0x7f05005e
			public const int gray = 2131034206;
			
			// aapt resource value: 0x7f050086
			public const int green = 2131034246;
			
			// aapt resource value: 0x7f05004c
			public const int greenyellow = 2131034188;
			
			// aapt resource value: 0x7f05002c
			public const int honeydew = 2131034156;
			
			// aapt resource value: 0x7f050019
			public const int hotpink = 2131034137;
			
			// aapt resource value: 0x7f050041
			public const int indianred = 2131034177;
			
			// aapt resource value: 0x7f05006f
			public const int indigo = 2131034223;
			
			// aapt resource value: 0x7f050002
			public const int ivory = 2131034114;
			
			// aapt resource value: 0x7f05002e
			public const int khaki = 2131034158;
			
			// aapt resource value: 0x7f050033
			public const int lavender = 2131034163;
			
			// aapt resource value: 0x7f05000a
			public const int lavenderblush = 2131034122;
			
			// aapt resource value: 0x7f050064
			public const int lawngreen = 2131034212;
			
			// aapt resource value: 0x7f050007
			public const int lemonchiffon = 2131034119;
			
			// aapt resource value: 0x7f05004d
			public const int lightblue = 2131034189;
			
			// aapt resource value: 0x7f05002f
			public const int lightcoral = 2131034159;
			
			// aapt resource value: 0x7f050034
			public const int lightcyan = 2131034164;
			
			// aapt resource value: 0x7f050021
			public const int lightgoldenrodyellow = 2131034145;
			
			// aapt resource value: 0x7f050056
			public const int lightgreen = 2131034198;
			
			// aapt resource value: 0x7f05003d
			public const int lightgrey = 2131034173;
			
			// aapt resource value: 0x7f050014
			public const int lightpink = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int lightsalmon = 2131034134;
			
			// aapt resource value: 0x7f05007a
			public const int lightseagreen = 2131034234;
			
			// aapt resource value: 0x7f05005c
			public const int lightskyblue = 2131034204;
			
			// aapt resource value: 0x7f050066
			public const int lightslategray = 2131034214;
			
			// aapt resource value: 0x7f05004a
			public const int lightsteelblue = 2131034186;
			
			// aapt resource value: 0x7f050003
			public const int lightyellow = 2131034115;
			
			// aapt resource value: 0x7f050080
			public const int lime = 2131034240;
			
			// aapt resource value: 0x7f050076
			public const int limegreen = 2131034230;
			
			// aapt resource value: 0x7f050022
			public const int linen = 2131034146;
			
			// aapt resource value: 0x7f05001e
			public const int magenta = 2131034142;
			
			// aapt resource value: 0x7f050061
			public const int maroon = 2131034209;
			
			// aapt resource value: 0x7f05006b
			public const int mediumaquamarine = 2131034219;
			
			// aapt resource value: 0x7f050089
			public const int mediumblue = 2131034249;
			
			// aapt resource value: 0x7f050046
			public const int mediumorchid = 2131034182;
			
			// aapt resource value: 0x7f050055
			public const int mediumpurple = 2131034197;
			
			// aapt resource value: 0x7f050075
			public const int mediumseagreen = 2131034229;
			
			// aapt resource value: 0x7f050065
			public const int mediumslateblue = 2131034213;
			
			// aapt resource value: 0x7f050081
			public const int mediumspringgreen = 2131034241;
			
			// aapt resource value: 0x7f050070
			public const int mediumturquoise = 2131034224;
			
			// aapt resource value: 0x7f050042
			public const int mediumvioletred = 2131034178;
			
			// aapt resource value: 0x7f050092
			public const int menuend = 2131034258;
			
			// aapt resource value: 0x7f050091
			public const int menustart = 2131034257;
			
			// aapt resource value: 0x7f05007c
			public const int midnightblue = 2131034236;
			
			// aapt resource value: 0x7f050026
			public const int mintcream = 2131034150;
			
			// aapt resource value: 0x7f05000d
			public const int mistyrose = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int moccasin = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int navajowhite = 2131034128;
			
			// aapt resource value: 0x7f05008b
			public const int navy = 2131034251;
			
			// aapt resource value: 0x7f050090
			public const int numend = 2131034256;
			
			// aapt resource value: 0x7f05008f
			public const int numstart = 2131034255;
			
			// aapt resource value: 0x7f050020
			public const int oldlace = 2131034144;
			
			// aapt resource value: 0x7f05005f
			public const int olive = 2131034207;
			
			// aapt resource value: 0x7f050068
			public const int olivedrab = 2131034216;
			
			// aapt resource value: 0x7f050096
			public const int optend = 2131034262;
			
			// aapt resource value: 0x7f050095
			public const int optstart = 2131034261;
			
			// aapt resource value: 0x7f050015
			public const int orange = 2131034133;
			
			// aapt resource value: 0x7f05001b
			public const int orangered = 2131034139;
			
			// aapt resource value: 0x7f05003b
			public const int orchid = 2131034171;
			
			// aapt resource value: 0x7f050030
			public const int palegoldenrod = 2131034160;
			
			// aapt resource value: 0x7f050053
			public const int palegreen = 2131034195;
			
			// aapt resource value: 0x7f05004b
			public const int paleturquoise = 2131034187;
			
			// aapt resource value: 0x7f050039
			public const int palevioletred = 2131034169;
			
			// aapt resource value: 0x7f05000b
			public const int papayawhip = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int peachpuff = 2131034129;
			
			// aapt resource value: 0x7f050040
			public const int peru = 2131034176;
			
			// aapt resource value: 0x7f050013
			public const int pink = 2131034131;
			
			// aapt resource value: 0x7f05008e
			public const int pluend = 2131034254;
			
			// aapt resource value: 0x7f050036
			public const int plum = 2131034166;
			
			// aapt resource value: 0x7f05008d
			public const int plustart = 2131034253;
			
			// aapt resource value: 0x7f050049
			public const int powderblue = 2131034185;
			
			// aapt resource value: 0x7f050060
			public const int purple = 2131034208;
			
			// aapt resource value: 0x7f05001f
			public const int red = 2131034143;
			
			// aapt resource value: 0x7f050045
			public const int rosybrown = 2131034181;
			
			// aapt resource value: 0x7f050073
			public const int royalblue = 2131034227;
			
			// aapt resource value: 0x7f050058
			public const int saddlebrown = 2131034200;
			
			// aapt resource value: 0x7f050024
			public const int salmon = 2131034148;
			
			// aapt resource value: 0x7f05002a
			public const int sandybrown = 2131034154;
			
			// aapt resource value: 0x7f050078
			public const int seagreen = 2131034232;
			
			// aapt resource value: 0x7f050009
			public const int seashell = 2131034121;
			
			// aapt resource value: 0x7f050050
			public const int sienna = 2131034192;
			
			// aapt resource value: 0x7f050043
			public const int silver = 2131034179;
			
			// aapt resource value: 0x7f05005d
			public const int skyblue = 2131034205;
			
			// aapt resource value: 0x7f050069
			public const int slateblue = 2131034217;
			
			// aapt resource value: 0x7f050067
			public const int slategray = 2131034215;
			
			// aapt resource value: 0x7f050005
			public const int snow = 2131034117;
			
			// aapt resource value: 0x7f05007f
			public const int springgreen = 2131034239;
			
			// aapt resource value: 0x7f050072
			public const int steelblue = 2131034226;
			
			// aapt resource value: 0x7f05003e
			public const int tan = 2131034174;
			
			// aapt resource value: 0x7f050085
			public const int teal = 2131034245;
			
			// aapt resource value: 0x7f05003c
			public const int thistle = 2131034172;
			
			// aapt resource value: 0x7f05001a
			public const int tomato = 2131034138;
			
			// aapt resource value: 0x7f050074
			public const int turquoise = 2131034228;
			
			// aapt resource value: 0x7f050031
			public const int violet = 2131034161;
			
			// aapt resource value: 0x7f050029
			public const int wheat = 2131034153;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			// aapt resource value: 0x7f050027
			public const int whitesmoke = 2131034151;
			
			// aapt resource value: 0x7f050004
			public const int yellow = 2131034116;
			
			// aapt resource value: 0x7f050051
			public const int yellowgreen = 2131034193;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06000b
			public const int buttonsEnterHeight = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int buttonsEscapeHeight = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int buttonsLeftWidth = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int buttonsPadding = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int buttonsRightWidth = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int keyHeight = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int keyWidth = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int keysHeight = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int lcdAreaHeight = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int lcdAreaHeightHor = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int lcdAreaWidth = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int lcdHeight = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int lcdWidth = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int banner = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int exec_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fncs_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int menu_bg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int num_bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int opts_bg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int plu_bg = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080007
			public const int Buttons = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int Buttons1 = 2131230728;
			
			// aapt resource value: 0x7f080035
			public const int Buttons10 = 2131230773;
			
			// aapt resource value: 0x7f08003a
			public const int Buttons11 = 2131230778;
			
			// aapt resource value: 0x7f08000d
			public const int Buttons2 = 2131230733;
			
			// aapt resource value: 0x7f080012
			public const int Buttons3 = 2131230738;
			
			// aapt resource value: 0x7f080017
			public const int Buttons4 = 2131230743;
			
			// aapt resource value: 0x7f08001c
			public const int Buttons5 = 2131230748;
			
			// aapt resource value: 0x7f080021
			public const int Buttons6 = 2131230753;
			
			// aapt resource value: 0x7f080026
			public const int Buttons7 = 2131230758;
			
			// aapt resource value: 0x7f08002b
			public const int Buttons8 = 2131230763;
			
			// aapt resource value: 0x7f080030
			public const int Buttons9 = 2131230768;
			
			// aapt resource value: 0x7f080040
			public const int ButtonsLeft = 2131230784;
			
			// aapt resource value: 0x7f080041
			public const int ButtonsRight = 2131230785;
			
			// aapt resource value: 0x7f080009
			public const int button1_1 = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int button1_2 = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int button1_3 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int button1_4 = 2131230732;
			
			// aapt resource value: 0x7f080011
			public const int button1_5 = 2131230737;
			
			// aapt resource value: 0x7f080016
			public const int button1_6 = 2131230742;
			
			// aapt resource value: 0x7f08000e
			public const int button2_1 = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int button2_2 = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int button2_3 = 2131230736;
			
			// aapt resource value: 0x7f08001b
			public const int button2_4 = 2131230747;
			
			// aapt resource value: 0x7f080020
			public const int button2_5 = 2131230752;
			
			// aapt resource value: 0x7f080025
			public const int button2_6 = 2131230757;
			
			// aapt resource value: 0x7f08003b
			public const int button2_7 = 2131230779;
			
			// aapt resource value: 0x7f08002a
			public const int button2_8 = 2131230762;
			
			// aapt resource value: 0x7f080013
			public const int button3_1 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int button3_2 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int button3_3 = 2131230741;
			
			// aapt resource value: 0x7f080027
			public const int button3_4 = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int button3_5 = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int button3_6 = 2131230761;
			
			// aapt resource value: 0x7f08003c
			public const int button3_7 = 2131230780;
			
			// aapt resource value: 0x7f08002f
			public const int button3_8 = 2131230767;
			
			// aapt resource value: 0x7f080018
			public const int button4_1 = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int button4_2 = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int button4_3 = 2131230746;
			
			// aapt resource value: 0x7f08002c
			public const int button4_4 = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int button4_5 = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int button4_6 = 2131230766;
			
			// aapt resource value: 0x7f08003d
			public const int button4_7 = 2131230781;
			
			// aapt resource value: 0x7f080034
			public const int button4_8 = 2131230772;
			
			// aapt resource value: 0x7f08001d
			public const int button5_1 = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int button5_2 = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int button5_3 = 2131230751;
			
			// aapt resource value: 0x7f080031
			public const int button5_4 = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int button5_5 = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int button5_6 = 2131230771;
			
			// aapt resource value: 0x7f08003e
			public const int button5_7 = 2131230782;
			
			// aapt resource value: 0x7f080039
			public const int button5_8 = 2131230777;
			
			// aapt resource value: 0x7f080022
			public const int button6_1 = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int button6_2 = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int button6_3 = 2131230756;
			
			// aapt resource value: 0x7f080036
			public const int button6_4 = 2131230774;
			
			// aapt resource value: 0x7f080037
			public const int button6_5 = 2131230775;
			
			// aapt resource value: 0x7f080038
			public const int button6_6 = 2131230776;
			
			// aapt resource value: 0x7f08003f
			public const int button6_7 = 2131230783;
			
			// aapt resource value: 0x7f080002
			public const int horLayLCD1 = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int horTop = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int imageView1 = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int layAll = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int layImage = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int textView1 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int textView2 = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int Amount = 2130968581;
			
			// aapt resource value: 0x7f040014
			public const int Correct = 2130968596;
			
			// aapt resource value: 0x7f040019
			public const int Customer = 2130968601;
			
			// aapt resource value: 0x7f040008
			public const int Document = 2130968584;
			
			// aapt resource value: 0x7f04001b
			public const int Drawer = 2130968603;
			
			// aapt resource value: 0x7f04001f
			public const int Enter = 2130968607;
			
			// aapt resource value: 0x7f04001c
			public const int Escape = 2130968604;
			
			// aapt resource value: 0x7f040006
			public const int In = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int LCD1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int LCD2 = 2130968579;
			
			// aapt resource value: 0x7f040015
			public const int Num0 = 2130968597;
			
			// aapt resource value: 0x7f040011
			public const int Num1 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int Num2 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int Num3 = 2130968595;
			
			// aapt resource value: 0x7f04000e
			public const int Num4 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int Num5 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int Num6 = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int Num7 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int Num8 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int Num9 = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int Option = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int Out = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int PLU = 2130968580;
			
			// aapt resource value: 0x7f04001d
			public const int Paper = 2130968605;
			
			// aapt resource value: 0x7f040009
			public const int Price = 2130968585;
			
			// aapt resource value: 0x7f040018
			public const int Program = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int Report = 2130968599;
			
			// aapt resource value: 0x7f04001a
			public const int Seller = 2130968602;
			
			// aapt resource value: 0x7f040016
			public const int Seperator = 2130968598;
			
			// aapt resource value: 0x7f04001e
			public const int Subtotal = 2130968606;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int ButtonBar = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int ButtonBarButton = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int EnterExitStyle = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int FncsStyle = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int FullscreenTheme = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int MenuStyle = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int NumStyle = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int OptsStyle = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int PluStyle = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ButtonBarContainerTheme = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int ButtonBarContainerTheme_buttonBarButtonStyle = 1;
			
			// aapt resource value: 0
			public const int ButtonBarContainerTheme_buttonBarStyle = 0;
			
			public static int[] CustomFonts = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int CustomFonts_customFont = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
