//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3082.
// 
namespace PromotionServer.HuginWSCF {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Hugin Web ServiceSoap", Namespace="http://localhost/HuginWebSite/")]
    public partial class HuginWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public HuginWebService() {
            this.Url = "http://localhost/HuginWss/Points.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/HuginWebSite/GetPoint", RequestNamespace="http://localhost/HuginWebSite/", ResponseNamespace="http://localhost/HuginWebSite/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetPoint(string code) {
            object[] results = this.Invoke("GetPoint", new object[] {
                        code});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPoint(string code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPoint", new object[] {
                        code}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndGetPoint(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/HuginWebSite/Add", RequestNamespace="http://localhost/HuginWebSite/", ResponseNamespace="http://localhost/HuginWebSite/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Add(string code, int documentId, long points) {
            object[] results = this.Invoke("Add", new object[] {
                        code,
                        documentId,
                        points});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAdd(string code, int documentId, long points, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Add", new object[] {
                        code,
                        documentId,
                        points}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndAdd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/HuginWebSite/Update", RequestNamespace="http://localhost/HuginWebSite/", ResponseNamespace="http://localhost/HuginWebSite/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Update(string code, int documentId, long points) {
            object[] results = this.Invoke("Update", new object[] {
                        code,
                        documentId,
                        points});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(string code, int documentId, long points, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        code,
                        documentId,
                        points}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUpdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
